export const movies = [
  {
    id: crypto.randomUUID(),
    name: "Iron Man",
    description: "Tony Stark builds a high-tech suit to save the world.",
    genre: "Action/Adventure/Sci-fi",
    rating: 4,
    price: 100,
    thumbnail: "iron-man.jpg",
  },
  {
    id: crypto.randomUUID(),
    name: "The Dark Knight",
    description: "Batman faces the Joker, a criminal mastermind.",
    genre: "Action/Crime/Drama",
    rating: 5,
    price: 120,
    thumbnail: "The-Dark-Knight.jpg",
  },
  {
    id: crypto.randomUUID(),
    name: "Inception",
    description: "A thief who steals corporate secrets through dream-sharing.",
    genre: "Action/Sci-fi/Thriller",
    rating: 3,
    price: 110,
    thumbnail: "Inception.jpg",
  },
  {
    id: crypto.randomUUID(),
    name: "Avengers: Endgame",
    description: "The Avengers assemble for a final showdown.",
    genre: "Action/Adventure/Fantasy",
    rating: 5,
    price: 150,
    thumbnail: "Avengers-Endgame.jpg",
  },
  {
    id: crypto.randomUUID(),
    name: "Interstellar",
    description: "A team travels through a wormhole in space.",
    genre: "Adventure/Drama/Sci-fi",
    rating: 4,
    price: 130,
    thumbnail: "Interstellar.jpg",
  },
  {
    id: crypto.randomUUID(),
    name: "Spider-Man: No Way Home",
    description: "Peter Parker faces multiverse chaos.",
    genre: "Action/Adventure/Fantasy",
    rating: 5,
    price: 115,
    thumbnail: "Spider-Man-No-Way-Home.jpg",
  },
  {
    id: crypto.randomUUID(),
    name: "Joker",
    description: "A mentally troubled comedian becomes the Joker.",
    genre: "Crime/Drama/Thriller",
    rating: 5,
    price: 95,
    thumbnail: "Joker.jpg",
  },
  {
    id: crypto.randomUUID(),
    name: "Black Panther",
    description: "T’Challa returns to Wakanda as king.",
    genre: "Action/Adventure/Sci-fi",
    rating: 4,
    price: 105,
    thumbnail: "Black-Panther.jpg",
  },
  {
    id: crypto.randomUUID(),
    name: "Doctor Strange",
    description: "A neurosurgeon turns into a master of mystic arts.",
    genre: "Action/Adventure/Fantasy",
    rating: 3,
    price: 100,
    thumbnail: "Doctor-Strange.jpeg",
  },
];
